version: '3.1'

services:
  mysql-olpt:
    image: mysql:latest
    container_name: mysql-olpt
    environment:
      MYSQL_ROOT_PASSWORD: root
      
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mysql-olpt-data:/var/lib/mysql
    networks:
      - common

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - common
volumes:
  mysql-olpt-data:

networks:
  common:
    driver: bridge
  