version: '3.1'

services:
  mysql-olpt:
    image: mysql:8.0.29
    container_name: mysql-oltp
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./sql/oltpSchema.sql:/docker-entrypoint-initdb.d/otlpSchema.sql
      - mysql-olpt-data:/var/lib/mysql
    networks:
      - common

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - common

  hadoop-namenode:
    build:
      context: ./containers/hadoop-namenode
      dockerfile: Dockerfile
    container_name: hadoop-namenode
    hostname: hadoop-namenode
    ports:
      - 9870:9870
      - 8088:8088
      - 19888:19888
    environment:
      - CLUSTER_NAME=hadoop-cluster
    networks:
      - common
    depends_on:
      - hadoop-datanode01
    volumes:
      - namenode-data:/hadoop/dfs/name

  hadoop-datanode01:
    build: 
      context: ./containers/hadoop-datanode
      dockerfile: Dockerfile
    container_name: hadoop-datanode01
    hostname: hadoop-datanode01
    environment:
      - "HADOOP_MASTER=hadoopmaster"
    networks:
      - common
    volumes:
      - datanode01-data:/hadoop/dfs/data

  spark-master:
    image: sparkbase
    container_name: spark-master
    ports:
      - 9090:8081
      - 7077:7077
    volumes:
      - ./apps:/opt/spark-3.4.2-bin-hadoop3-scala2.13/spark-apps
      - ./data:/opt/spark-3.4.2-bin-hadoop3-scala2.13/spark-data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
    networks:
      - common
    command: /bin/sh -c "/start-spark.sh"

  spark-worker-a:
    image: sparkbase
    container_name: spark-worker-a
    ports:
      - 9091:8081
      - 7000:7000
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
      - ./apps:/opt/spark-3.4.2-bin-hadoop3-scala2.13/spark-apps
      - ./data:/opt/spark-3.4.2-bin-hadoop3-scala2.13/spark-data
    networks:
      - common
    command: /bin/sh -c "/start-spark.sh"

  postgres-metastore:
    image: postgres:13
    container_name: postgres-metastore
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    volumes:
      - ./sql/postgreInit.sql:/docker-entrypoint-initdb.d/postgreInit.sql
      - postgres-metastore-data:/var/lib/postgresql/data
    networks:
      - common

  hive:
    build: 
      context: ./containers/hive
      dockerfile: Dockerfile
    container_name: hive
    depends_on:
      - postgres-metastore
    networks:
      - common
    
volumes:
  mysql-olpt-data:
  datanode01-data:
  namenode-data:
  postgres-metastore-data:

networks:
  common:
    driver: bridge
  